In [2]:
import csv
import pandas as pd
import numpy as np

In [13]:
file = open('../../Thales/log.txt', 'r')
line = file.readlines(1500)
title = line[-2:-1]
col = [x.strip(' ') for x in [i.split('|') for i in line[-2:-1]][0]]
col = col[1:-1]
data_list=[]
line = file.readline()
count=0
while ((count<2000) & (line != title[0])):
    #line = file.readline()
    line = [x.strip(' ') for x in line.split('|')][1:-1]
    data_list.append(line)
    count = count + 1
    #print(count)
    line = file.readline()
#line = file.readline()
file.close()
'''
data = pd.DataFrame(data_list,columns=col)
data = data.iloc[:-6,0:]

for name in ['lat', 'lon','velocity','heading','vertrate','baroaltitude','geoaltitude','lastposupdate','lastcontact']:
    data[name] = pd.to_numeric(data[name], errors='coerce')
'''
'''
if (line==title[0]):
    print('Yes')
else:
    print(line)
    print(title[0])
'''
data_list[-6:-1]

[['1520207471',
  '7800ac',
  '26.52099609375',
  '119.7595790647111',
  '247.7447149614573',
  '32.53506715793501',
  '6.177280000000001',
  'CXA8063',
  'false',
  'false',
  'false',
  '0733',
  '7680.96',
  '7863.84',
  '1520207462.183',
  '1520207465.95',
  '1520204400'],
 ['1520207472',
  '7800ac',
  '26.52099609375',
  '119.7595790647111',
  '247.7447149614573',
  '32.53506715793501',
  '6.177280000000001',
  'CXA8063',
  'false',
  'false',
  'false',
  '0733',
  '7680.96',
  '7863.84',
  '1520207462.183',
  '1520207465.95',
  '1520204400'],
 ['1520207473',
  '7800ac',
  '26.52099609375',
  '119.7595790647111',
  '247.7447149614573',
  '32.53506715793501',
  '6.177280000000001',
  'CXA8063',
  'false',
  'false',
  'false',
  '0733',
  '7680.96',
  '7863.84',
  '1520207462.183',
  '1520207465.95',
  '1520204400'],
 ['1520207474',
  '7800ac',
  '26.52099609375',
  '119.7595790647111',
  '247.7447149614573',
  '32.53506715793501',
  '6.177280000000001',
  'CXA8063',
  'false',
  'false',
  'false',
  '0733',
  '7680.96',
  '7863.84',
  '1520207462.183',
  '1520207465.95',
  '1520204400'],
 []]